apiVersion: v1
kind: ConfigMap
metadata:
  name: payments-api-config
data:
  ASPNETCORE_ENVIRONMENT: Production
  RabbitMq__Host: rabbitmq
  RabbitMq__Port: "5672"
  RabbitMq__VirtualHost: /
  RabbitMq__OrderPlacedQueue: payments-order-placed
  Payment__ApprovalLimit: "100.00"
  Sqs__Region: us-east-1
  Sqs__QueueUrl: "https://sqs.us-east-1.amazonaws.com/ACCOUNT_ID/fcg-fase3-payment-processed"
