apiVersion: v1
kind: Secret
metadata:
  name: payments-api-secrets
type: Opaque
stringData:
  RabbitMq__Username: replace-me
  RabbitMq__Password: replace-me
  AWS_ACCESS_KEY_ID: "<temporary-payments-role-access-key>"
  AWS_SECRET_ACCESS_KEY: "<temporary-payments-role-secret-key>"
  AWS_SESSION_TOKEN: "<temporary-payments-role-session-token>"
